model_checkpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  dirpath: ${output_dir}/checkpoints
  save_top_k: -1
  monitor: val_loss
  mode: min
  save_last: true
  filename: "{epoch:02d}-{val_loss:.2f}"
  save_weights_only: true
