# @package model.vima_instance_transform
_target_: cogelot.data.transforms.ChainTransform
transforms:
  - _target_: cogelot.data.transforms.TextualDescriptionTransform
  - _target_: cogelot.data.transforms.GobbledyGookPromptWordTransform
