defaults:
  - default
  - override callbacks:
      - model_summary
      - rich_progress
  - override logger: wandb_evaluation
  - _self_

max_epochs: 1

# The evaluation is going to be deterministic so it's consistent per run/model
deterministic: True
inference_mode: True
