_target_: cogelot.modules.action_encoders.TokenPerAxisActionEmbedder
pose_action_tokenizer:
  _target_: cogelot.modules.tokenizers.PoseActionTokenizer
max_num_action_bins: 100
num_axes: 14
embed_dim: ${model.policy.embed_dim}
