# This is their implementation of their VIMA transformer decoder
_target_: cogelot.nn.decoders.VIMADecoder
vima_xattn_gpt:
  _target_: vima.nn.XAttnGPT
  # Hyperparams taken from Table9 in the paper
  embd_dim: ${...embed_dim}
  n_layer: 11
  n_head: 24
  dropout: 0.1
  xattn_n_head: 24
  xattn_ff_expanding: 4
  xattn_n_positions: 256
  use_geglu: True
