_target_: cogelot.modules.action_encoders.VIMAContinuousActionEmbedder
pose_action_tokenizer:
  _target_: cogelot.modules.tokenizers.PoseActionTokenizer
embedder_per_pose_action:
  pose0_position:
    _target_: vima.nn.ContinuousActionEmbedding
    output_dim: 256
    input_dim: 3
    hidden_dim: 256
    hidden_depth: 1
  pose1_position:
    _target_: vima.nn.ContinuousActionEmbedding
    output_dim: 256
    input_dim: 3
    hidden_dim: 256
    hidden_depth: 1
  pose0_rotation:
    _target_: vima.nn.ContinuousActionEmbedding
    output_dim: 256
    input_dim: 4
    hidden_dim: 256
    hidden_depth: 1
  pose1_rotation:
    _target_: vima.nn.ContinuousActionEmbedding
    output_dim: 256
    input_dim: 4
    hidden_dim: 256
    hidden_depth: 1
post_layer:
  _target_: torch.nn.Linear
  in_features:
    _target_: builtins.sum
    _convert_: all
    _args_:
      - - ${.....embedder_per_pose_action.pose0_position.output_dim}
        - ${.....embedder_per_pose_action.pose1_position.output_dim}
        - ${.....embedder_per_pose_action.pose0_rotation.output_dim}
        - ${.....embedder_per_pose_action.pose1_rotation.output_dim}
  out_features: ${...embed_dim}
